# Discord Settings
BotToken: "YOUR_BOT_TOKEN"
Channel: "Channel_ID"
Exclude: {
  "FolderX":            true,
  "FolderY":            true,
  "FolderZ":            true
}

# FTP Settings
IP: "X.X.X.X"
Port: "42"
User: "XYZ"
PW: "12345"